package com.along.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.along.entity.Example;

public interface CrudDao<T,D extends Example<D>> {
	
	
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Aug 14 13:12:44 CST 2017
     */
    long countByExample(D example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Aug 14 13:12:44 CST 2017
     */
    int deleteByExample(D example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Aug 14 13:12:44 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Aug 14 13:12:44 CST 2017
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Aug 14 13:12:44 CST 2017
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Aug 14 13:12:44 CST 2017
     */
    List<T> selectByExample(D example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Aug 14 13:12:44 CST 2017
     */
    T selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Aug 14 13:12:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") T record, @Param("example") D example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Aug 14 13:12:44 CST 2017
     */
    int updateByExample(@Param("record") T record, @Param("example") D example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Aug 14 13:12:44 CST 2017
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Aug 14 13:12:44 CST 2017
     */
    int updateByPrimaryKey(T record);
    
}
