package com.along.entity;

import java.util.Date;

public class Article extends DataEntity<Article>{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.name
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.category
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.comments
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private Integer comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.shares
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private Integer shares;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.goods
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private Integer goods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.create_by
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.create_date
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.update_date
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.del_flag
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.remarks
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.update_by
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.blog_id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.category_id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.hits
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private Integer hits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.open
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private Integer open;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.content
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.id
     *
     * @return the value of t_article.id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.id
     *
     * @param id the value for t_article.id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.name
     *
     * @return the value of t_article.name
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.name
     *
     * @param name the value for t_article.name
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.category
     *
     * @return the value of t_article.category
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.category
     *
     * @param category the value for t_article.category
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.comments
     *
     * @return the value of t_article.comments
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public Integer getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.comments
     *
     * @param comments the value for t_article.comments
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setComments(Integer comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.shares
     *
     * @return the value of t_article.shares
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public Integer getShares() {
        return shares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.shares
     *
     * @param shares the value for t_article.shares
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setShares(Integer shares) {
        this.shares = shares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.goods
     *
     * @return the value of t_article.goods
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public Integer getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.goods
     *
     * @param goods the value for t_article.goods
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setGoods(Integer goods) {
        this.goods = goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.create_by
     *
     * @return the value of t_article.create_by
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.create_by
     *
     * @param createBy the value for t_article.create_by
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.create_date
     *
     * @return the value of t_article.create_date
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.create_date
     *
     * @param createDate the value for t_article.create_date
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.update_date
     *
     * @return the value of t_article.update_date
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.update_date
     *
     * @param updateDate the value for t_article.update_date
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.del_flag
     *
     * @return the value of t_article.del_flag
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.del_flag
     *
     * @param delFlag the value for t_article.del_flag
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.remarks
     *
     * @return the value of t_article.remarks
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.remarks
     *
     * @param remarks the value for t_article.remarks
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.update_by
     *
     * @return the value of t_article.update_by
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.update_by
     *
     * @param updateBy the value for t_article.update_by
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.blog_id
     *
     * @return the value of t_article.blog_id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.blog_id
     *
     * @param blogId the value for t_article.blog_id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setBlogId(String blogId) {
        this.blogId = blogId == null ? null : blogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.category_id
     *
     * @return the value of t_article.category_id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.category_id
     *
     * @param categoryId the value for t_article.category_id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.hits
     *
     * @return the value of t_article.hits
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public Integer getHits() {
        return hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.hits
     *
     * @param hits the value for t_article.hits
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setHits(Integer hits) {
        this.hits = hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.open
     *
     * @return the value of t_article.open
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public Integer getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.open
     *
     * @param open the value for t_article.open
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setOpen(Integer open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.content
     *
     * @return the value of t_article.content
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.content
     *
     * @param content the value for t_article.content
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}