package com.along.entity;

import java.util.Date;

public class Comment extends DataEntity<Comment>{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.article_id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.create_by
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.create_date
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.update_date
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.del_flag
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.remarks
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.update_by
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.recomment_id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String recommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.content
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.id
     *
     * @return the value of t_comment.id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.id
     *
     * @param id the value for t_comment.id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.article_id
     *
     * @return the value of t_comment.article_id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.article_id
     *
     * @param articleId the value for t_comment.article_id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId == null ? null : articleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.create_by
     *
     * @return the value of t_comment.create_by
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.create_by
     *
     * @param createBy the value for t_comment.create_by
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.create_date
     *
     * @return the value of t_comment.create_date
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.create_date
     *
     * @param createDate the value for t_comment.create_date
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.update_date
     *
     * @return the value of t_comment.update_date
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.update_date
     *
     * @param updateDate the value for t_comment.update_date
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.del_flag
     *
     * @return the value of t_comment.del_flag
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.del_flag
     *
     * @param delFlag the value for t_comment.del_flag
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.remarks
     *
     * @return the value of t_comment.remarks
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.remarks
     *
     * @param remarks the value for t_comment.remarks
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.update_by
     *
     * @return the value of t_comment.update_by
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.update_by
     *
     * @param updateBy the value for t_comment.update_by
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.recomment_id
     *
     * @return the value of t_comment.recomment_id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getRecommentId() {
        return recommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.recomment_id
     *
     * @param recommentId the value for t_comment.recomment_id
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setRecommentId(String recommentId) {
        this.recommentId = recommentId == null ? null : recommentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.content
     *
     * @return the value of t_comment.content
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.content
     *
     * @param content the value for t_comment.content
     *
     * @mbg.generated Wed Sep 06 20:28:38 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}