package com.along.entity;

import java.util.Date;

public class Log extends DataEntity<Log>{
	
	
	
    @Override
	public String toString() {
		return "Log [id=" + id + ", time=" + time + ", url=" + url
				+ ", method=" + method + ", description=" + description
				+ ", requestIp=" + requestIp + ", exceptionDetail="
				+ exceptionDetail + ", exceptionCode=" + exceptionCode
				+ ", createBy=" + createBy + ", createDate=" + createDate
				+ ", updateBy=" + updateBy + ", updateDate=" + updateDate
				+ ", remarks=" + remarks + ", delFlag=" + delFlag + "]";
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.id
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.time
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    private Long time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.url
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.method
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.description
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.request_ip
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    private String requestIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.exception_detail
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    private String exceptionDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.exception_code
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    private String exceptionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.create_by
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.create_date
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.update_by
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.update_date
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.remarks
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.del_flag
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.id
     *
     * @return the value of sys_log.id
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.id
     *
     * @param id the value for sys_log.id
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.time
     *
     * @return the value of sys_log.time
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.time
     *
     * @param time the value for sys_log.time
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.url
     *
     * @return the value of sys_log.url
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.url
     *
     * @param url the value for sys_log.url
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.method
     *
     * @return the value of sys_log.method
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.method
     *
     * @param method the value for sys_log.method
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.description
     *
     * @return the value of sys_log.description
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.description
     *
     * @param description the value for sys_log.description
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.request_ip
     *
     * @return the value of sys_log.request_ip
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public String getRequestIp() {
        return requestIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.request_ip
     *
     * @param requestIp the value for sys_log.request_ip
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp == null ? null : requestIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.exception_detail
     *
     * @return the value of sys_log.exception_detail
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public String getExceptionDetail() {
        return exceptionDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.exception_detail
     *
     * @param exceptionDetail the value for sys_log.exception_detail
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public void setExceptionDetail(String exceptionDetail) {
        this.exceptionDetail = exceptionDetail == null ? null : exceptionDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.exception_code
     *
     * @return the value of sys_log.exception_code
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public String getExceptionCode() {
        return exceptionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.exception_code
     *
     * @param exceptionCode the value for sys_log.exception_code
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public void setExceptionCode(String exceptionCode) {
        this.exceptionCode = exceptionCode == null ? null : exceptionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.create_by
     *
     * @return the value of sys_log.create_by
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.create_by
     *
     * @param createBy the value for sys_log.create_by
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.create_date
     *
     * @return the value of sys_log.create_date
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.create_date
     *
     * @param createDate the value for sys_log.create_date
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.update_by
     *
     * @return the value of sys_log.update_by
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.update_by
     *
     * @param updateBy the value for sys_log.update_by
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.update_date
     *
     * @return the value of sys_log.update_date
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.update_date
     *
     * @param updateDate the value for sys_log.update_date
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.remarks
     *
     * @return the value of sys_log.remarks
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.remarks
     *
     * @param remarks the value for sys_log.remarks
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.del_flag
     *
     * @return the value of sys_log.del_flag
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.del_flag
     *
     * @param delFlag the value for sys_log.del_flag
     *
     * @mbg.generated Fri Aug 25 14:54:31 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}