package com.along.entity;

public class UrlEntity extends DataEntity<UrlEntity>{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.id
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.name
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.url
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.method_type
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    private String methodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.description
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.del_flag
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.test_params
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    private String testParams;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.id
     *
     * @return the value of sys_url.id
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.id
     *
     * @param id the value for sys_url.id
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.name
     *
     * @return the value of sys_url.name
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.name
     *
     * @param name the value for sys_url.name
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.url
     *
     * @return the value of sys_url.url
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.url
     *
     * @param url the value for sys_url.url
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.method_type
     *
     * @return the value of sys_url.method_type
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    public String getMethodType() {
        return methodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.method_type
     *
     * @param methodType the value for sys_url.method_type
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    public void setMethodType(String methodType) {
        this.methodType = methodType == null ? null : methodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.description
     *
     * @return the value of sys_url.description
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.description
     *
     * @param description the value for sys_url.description
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.del_flag
     *
     * @return the value of sys_url.del_flag
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.del_flag
     *
     * @param delFlag the value for sys_url.del_flag
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.test_params
     *
     * @return the value of sys_url.test_params
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    public String getTestParams() {
        return testParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.test_params
     *
     * @param testParams the value for sys_url.test_params
     *
     * @mbg.generated Sat Sep 09 14:19:58 CST 2017
     */
    public void setTestParams(String testParams) {
        this.testParams = testParams == null ? null : testParams.trim();
    }
}