package com.along.entity;

public class UrlEntity extends DataEntity<UrlEntity>{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.id
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.name
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.title
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.url
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.method_type
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    private String methodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.description
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.file_name
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.file_type
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_url.file_path
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    private String filePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.id
     *
     * @return the value of sys_url.id
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.id
     *
     * @param id the value for sys_url.id
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.name
     *
     * @return the value of sys_url.name
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.name
     *
     * @param name the value for sys_url.name
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.title
     *
     * @return the value of sys_url.title
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.title
     *
     * @param title the value for sys_url.title
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.url
     *
     * @return the value of sys_url.url
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.url
     *
     * @param url the value for sys_url.url
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.method_type
     *
     * @return the value of sys_url.method_type
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public String getMethodType() {
        return methodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.method_type
     *
     * @param methodType the value for sys_url.method_type
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public void setMethodType(String methodType) {
        this.methodType = methodType == null ? null : methodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.description
     *
     * @return the value of sys_url.description
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.description
     *
     * @param description the value for sys_url.description
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.file_name
     *
     * @return the value of sys_url.file_name
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.file_name
     *
     * @param fileName the value for sys_url.file_name
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.file_type
     *
     * @return the value of sys_url.file_type
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.file_type
     *
     * @param fileType the value for sys_url.file_type
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_url.file_path
     *
     * @return the value of sys_url.file_path
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_url.file_path
     *
     * @param filePath the value for sys_url.file_path
     *
     * @mbg.generated Thu Aug 17 20:56:23 CST 2017
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }
}